[package]
name = "helix_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.17.2"
winit = "0.28.7"
glam = "0.24"
pollster = "0.3"
gltf = "1.3"
bytemuck = { version = "1.9", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
cgmath = "0.18"